### ISSUE TITLE
为剧本添加深度(大雾)

### ISSUE THREAD

**Issue by RimoChan** [BeautyYuYanli/StudyWithNineteen#1]
我 「晚上好……话说，你一点也不惊讶吗？」

时九 「惊讶？」

　我 「……在学校里遇到我。」

时九 「我居然忘了……」

　　她的声音严肃了起来，停住脚步站在了我的背后。

时九 「上次见面以来，我就有这样的疑惑了。」

时九 「不对、这样不对……
　　 　到底是怎么回事？」

　我 「不太明白，现在是什么话题？」

时九 「是你吧……还要再装下去吗？
　　 　你到底是谁？」

时九 「问法不太合适……应该说『你到底是什么怪物』。」

　我 「哈、哈哈哈，是那个吧，
　　 　每个人的心里都住着的那种怪物。
　　 　对吧，也有可爱的类型在里面。」

时九 「但你是那只怪物本身。
　　 　也许他们认不出你，但我知道。」

　　我不由自主地笑了出来。

　我 「讽刺……真是讽刺！
　　 　我是怪物那你又是什么？
　　 　你觉得那就是自己的样子吗？」

(编不下去了)

**Comment by BeautyyuYanli** [comment]
喵喵喵？？？
