### ISSUE TITLE
好难啊天

### ISSUE THREAD

**Issue by sandyzikun** [BeautyYuYanli/StudyWithNineteen#2]

**Comment by BeautyyuYanli** [comment]
诶嘿嘿欢迎点个star哦.

**Comment by BeautyyuYanli** [comment]
甚至还有朋友觉得太简单.我还加了个更魔鬼的挑战模式

**Comment by sandyzikun** [comment]
已经star+watch了哦\~，不过我不轻易fork别人东西，毕竟我也不知道怎么帮你们优化这个game抱歉啦
说实话人物立绘和剧情都蛮棒的，不过我觉得挑战模式。。。我就望洋兴叹了吧
