### ISSUE TITLE
你又爱记单词了

### ISSUE THREAD

**Issue by Ivan1105** [BeautyYuYanli/StudyWithNineteen#3]
##  To Dear BeautyYu,
    Glad to hear that you have been a nice Grade-Three boy. As an elder man, I'm giving my best wishes to you. Yo-yo, yo-yo do as the HK's laws say. Too young, to simple, sometimes naive.

**Comment by BeautyYuYanli** [comment]
faq

Ivan <notifications@github.com<mailto:notifications@github.com>> 于2019年9月14日周六 下午12:22写道：
To Dear BeautyYu,

Glad to hear that you have been a nice Grade-Three boy. As an elder man, I'm giving my best wishes to you. Yo-yo, yo-yo do as the HK's laws say. Too young, to simple, sometimes naive.

**Comment by BeautyyuYanli** [comment]
thank FAQr wishes

**Comment by Ivan1105** [comment]
Yeah, that♂s♂good

**Comment by BeautyyuYanli** [comment]
star please

**Comment by Ivan1105** [comment]
no,&nbsp;no&nbsp;star


---原始邮件---
发件人: &quot;BeautyYuYanli&quot;<notifications@github.com&gt;
发送时间: 2019年9月15日(星期日) 晚上10:15
收件人: &quot;BeautyYuYanli/StudyWithNineteen&quot;<StudyWithNineteen@noreply.github.com&gt;;
抄送: &quot;Ivan&quot;<1058267816@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [BeautyYuYanli/StudyWithNineteen] 你又爱记单词了 (#3)



star please
 
&mdash;
