### ISSUE TITLE
贵项目在线穿模了

### ISSUE THREAD

**Issue by huoxingdawang** [BeautyYuYanli/StudyWithNineteen#4]
如标题所示

当你把鼠标放在首页第四个按钮上的时候，他会变大

然后跑到下一行

然后缩小，回去，再下来

体验极差，根本点不上

**Comment by BeautyyuYanli** [comment]
是分辨率的问题。之前也出现过 调大间距就能解决 我的设备上是没问题了。不过这么说来还是需要调整emmm
