### ISSUE TITLE
贵项目优化极差

### ISSUE THREAD

**Issue by Ivan1105** [BeautyYuYanli/StudyWithNineteen#5]
一次性加载的图片资源太多了，还都是高清原图，响应要很久，天翼3G真是太快了

**Comment by Ivan1105** [comment]
还有，当存档代码太长时，会溢出框架

![Image](https://user-images.githubusercontent.com/35651468/74549488-b0e37800-4f8a-11ea-9c0b-5835a4df7391.png)

**Comment by BeautyyuYanli** [comment]
@Ivan1105 宁快来交pr啊

**Comment by BeautyyuYanli** [comment]
如果你不把成绩改成&^&(&^%^^(*&)(*$应该是不会溢出的.
